const htmlMock = '<dl class="Accordion" id="accordion">'
+ '<dt>Section 1</dt>'
+ '<dd>'
  + '<p>Section 1 Content...</p>'
+ '</dd>'
+ '<dt>Section 2</dt>'
+ '<dd>'
  + '<p>Section 2 Content...</p>'
+ '</dd>'
+ '<dt>Section 3</dt>'
+ '<dd>'
  + '<p>Section 3 Content...</p>'
+ '</dd>'
+ '<dt class="Accordion-ajaxSection">AJAX loaded content section</dt>'
+ '<dd>'
  + '<div class="Accordion-githubAvatarContent">'
    + '<img id="githubAvatar" alt="github-avatar">'
    + '</p>'
    + '<a target="_blank"></a>'
    + '</p>'
    + '<a target="_blank"></a>'
  + '</div>'
+ '</dd>'
+ '</dl>'

export default htmlMock
